blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60 * 2)(BlogListView.as_view()), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_item'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailing/urls.py
from django.urls import path

from mailing.apps import MailingConfig
from mailing.views import ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, MailingListView, \
    MailingCreateView, MailingUpdateView, MailingDeleteView, MailingLogListView, MainListView

app_name = MailingConfig.name

urlpatterns = [
    path('clients/', ClientListView.as_view(), name='clients_list'),
    path('clients/create/', ClientCreateView.as_view(), name='clients_create'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='clients_edit'),
    path('clients/delete/<int:pk>/', ClientDeleteView.as_view(), name='clients_delete'),

    path('mailings/', MailingListView.as_view(), name='mailings_list'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailings_create'),
    path('mailings/edit/<int:pk>/', MailingUpdateView.as_view(), name='mailings_edit'),
    path('mailings/delete/<int:pk>/', MailingDeleteView.as_view(), name='mailings_delete'),

    path('report/', MailingLogListView.as_view(), name='report_list'),


    path('', MainListView.as_view(), name='main_page'),
]

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, LogoutUserView, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),

    path('users_list/', UserListView.as_view(), name='users_list'),
    path('users_list/edit/<int:pk>/', UserUpdateView.as_view(), name='users_edit'),
]

mailing/models.py
from django.conf import settings
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    mailings_list = models.ManyToManyField('Mailing', blank=True, related_name='clients', verbose_name='Рассылка')
    email = models.EmailField(verbose_name='email клиента')
    full_name = models.CharField(max_length=200, verbose_name='ФИО')
    comment = models.TextField(max_length=300, verbose_name='Комментарий', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                                      verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.full_name} - {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'
        ordering = ('id',)


class Mailing(models.Model):
    PERIOD_DAILY = 'daily'
    PERIOD_WEEKLY = 'weekly'
    PERIOD_MONTHLY = 'monthly'
    PERIODS = (
        (PERIOD_DAILY, 'Ежедневная'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'created'
    STATUS_STARTED = 'started'
    STATUS_DONE = 'done'
    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    clients_list = models.ManyToManyField('Client', related_name='mailings', verbose_name='Клиент')
    mailing_name = models.CharField(max_length=200, verbose_name='Имя рассылки')
    time = models.TimeField(verbose_name='Время рассылки')
    period = models.CharField(default='Ежедневная', max_length=25, choices=PERIODS, verbose_name='Периодичность')
    status = models.CharField(default='Создана', max_length=25, choices=STATUSES, verbose_name='Статус')
    send_mail_subject = models.CharField(max_length=200, verbose_name='Тема письма')
    send_mail_message = models.TextField(max_length=1500, verbose_name='Текст письма')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                              verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.mailing_name}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'
        ordering = ('id',)


class MailingLog(models.Model):
    STATUS_OK = 'ok'
    STATUS_FAILED = 'failed'
    STATUSES = (
        (STATUS_OK, 'Успешно'),
        (STATUS_FAILED, 'Ошибка'),
    )

    mailing = models.ForeignKey('Mailing', on_delete=models.CASCADE, verbose_name='Рассылка')
    last_mailing = models.DateTimeField(verbose_name='Время последней попытки')
    status = models.CharField(max_length=25, choices=STATUSES, verbose_name='Статус')
    clients_full_name = models.TextField(verbose_name='ФИО клиентов')
    clients_email = models.TextField(verbose_name='email клиентов')
    mailing_name = models.CharField(max_length=200, verbose_name='Имя рассылки')
    error_message = models.TextField(verbose_name='Сообщение об ошибке', **NULLABLE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT,
                              verbose_name='Владелец', **NULLABLE)

    def __str__(self):
        return f'{self.mailing_name} - {self.last_mailing}'

    class Meta:
        verbose_name = 'Лог рассылки'
        verbose_name_plural = 'Логи рассылок'
        ordering = ('id',)

mailing/forms.py
from django import forms

from mailing.models import Client, Mailing


class StyleFormMixin():
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        fields = ('email', 'full_name', 'comment',)


class MailingForUserForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('clients_list', 'mailing_name', 'time', 'period', 'status', 'send_mail_subject', 'send_mail_message',)

    def __init__(self, *args, **kwargs):
        # Получаем текущего пользователя из аргументов формы.
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        if user:
            # Фильтруем клиентов, принадлежащих текущему пользователю.
            self.fields['clients_list'].queryset = Client.objects.filter(owner=user)
        else:
            # Если user = None, значит текущий пользователь это админ, ему доступен список всех клиентов.
            self.fields['clients_list'].queryset = Client.objects.all()


class MailingForManagerForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        fields = ('status', 'send_mail_subject', 'send_mail_message',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Если пользователь is_staff=True, то он может редактировать
        # только поле 'status', остальные поля только для чтения.
        self.fields['send_mail_subject'].widget.attrs['readonly'] = True
        self.fields['send_mail_message'].widget.attrs['readonly'] = True

mailing/views.py
from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.cache import cache
from django.http import Http404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from blog.models import Article
from mailing.cron import send_mail_make_report_for_all
from mailing.forms import ClientForm, MailingForUserForm, MailingForManagerForm
from mailing.models import Client, Mailing, MailingLog
from mailing.services import set_mailing_affiliation


class ClientListView(LoginRequiredMixin, ListView):
    model = Client

    def get_queryset(self):
        queryset = super().get_queryset()

        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ, то показываем всех клиентов.
        elif self.request.user.is_superuser:
            return queryset
        # Если обычный пользователь, то показываем только его клиентов.
        else:
            return queryset.filter(owner=self.request.user)


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients_list')

    def dispatch(self, request, *args, **kwargs):
        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if request.user.is_staff and not request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ или обычный пользователь, то доступ разрешен.
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()

        # Присваиваем в качестве владельца текущего пользователя.
        self.object.owner = self.request.user
        self.object = form.save()

        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailing:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ, то доступ разрешен к редактированию всех клиентов.
        elif self.request.user.is_superuser:
            return self.object
        # Если обычный пользователь, то доступ разрешен к редактированию только его клиентов.
        elif self.object.owner == self.request.user:
            return self.object
        else:
            raise Http404('Доступ запрещен')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailing:clients_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ, то доступ разрешен к удалению всех клиентов.
        elif self.request.user.is_superuser:
            return self.object
        # Если обычный пользователь, то доступ разрешен к удалению только его клиентов.
        elif self.object.owner == self.request.user:
            return self.object
        else:
            raise Http404('Доступ запрещен')


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing

    def get_queryset(self):
        queryset = super().get_queryset()

        # Если пользователь is_staff=True или is_superuser=True, то показываем все рассылки.
        if self.request.user.is_staff or self.request.user.is_superuser:
            return queryset
        # Если обычный пользователь, то показываем только его рассылки.
        else:
            return queryset.filter(owner=self.request.user)


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForUserForm
    success_url = reverse_lazy('mailing:mailings_list')

    def dispatch(self, request, *args, **kwargs):
        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if request.user.is_staff and not request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ или обычный пользователь, то доступ разрешен.
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save()

        # Присваиваем в качестве владельца текущего пользователя.
        self.object.owner = self.request.user
        self.object = form.save()

        # Явно задает у клиентов в поле mailings_list принадлежность (или ее отсутствие) к рассылке.
        set_mailing_affiliation(self.object)
        # Отправляем письмо и формируем отчет.
        send_mail_make_report_for_all()

        return super().form_valid(form)

    # Передаем текущего пользователя в качестве аргумента в формы, чтобы в списке clients_list можно
    # было выбирать только клиентов текущего пользователя.
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Если пользователь админ, то ему доступен выбор всех клиентов всех пользователей.
        if self.request.user.is_superuser:
            return kwargs
        # Если обычный пользователь, то ему доступен выбор только своих клиентов.
        else:
            kwargs['user'] = self.request.user
            return kwargs


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForUserForm
    success_url = reverse_lazy('mailing:mailings_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff=True или is_superuser=True, то разрешен доступ к редактированию всех рассылок.
        if self.request.user.is_staff or self.request.user.is_superuser:
            return self.object
        # Если обычный пользователь, то доступ разрешен к редактированию только его рассылок.
        elif self.object.owner == self.request.user:
            return self.object
        else:
            raise Http404('Доступ запрещен')

    def get_form_class(self, *args, **kwargs):
        if self.request.user == self.object.owner or self.request.user.is_superuser:
            # Вернуть форму MailingForUserForm для владельца рассылки или админа.
            return MailingForUserForm
        elif self.request.user.is_staff:
            # Вернуть форму MailingForManagerForm для пользователя с is_staff=True.
            return MailingForManagerForm
        else:
            # Вызвать 404 ошибку если ни одно условие не подошло.
            raise Http404

    def form_valid(self, form):
        self.object = form.save()

        # Явно задает у клиентов в поле mailings_list принадлежность (или ее отсутствие) к рассылке.
        set_mailing_affiliation(self.object)
        # Отправляем письмо и формируем отчет.
        send_mail_make_report_for_all()

        return super().form_valid(form)

    # Передаем текущего пользователя в качестве аргумента в формы, чтобы в списке clients_list можно
    # было выбирать только клиентов текущего пользователя.
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        # Обычному пользователю доступен выбор только собственных клиентов для clients_list.
        if self.request.user.is_superuser or self.request.user.is_staff:
            return kwargs
        else:
            kwargs['user'] = self.request.user
            return kwargs


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailing:mailings_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ, то доступ разрешен к удалению всех рассылок.
        elif self.request.user.is_superuser:
            return self.object
        # Если обычный пользователь, то доступ разрешен к удалению только его рассылок.
        elif self.object.owner == self.request.user:
            return self.object
        else:
            raise Http404('Доступ запрещен')


class MailingLogListView(LoginRequiredMixin, ListView):
    model = MailingLog

    def get_queryset(self):
        queryset = super().get_queryset()

        # Если пользователь is_staff=True и is_superuser=False, то вызываем ошибку.
        if self.request.user.is_staff and not self.request.user.is_superuser:
            raise Http404('Доступ запрещен')
        # Если пользователь админ, то показываем все отчеты.
        elif self.request.user.is_superuser:
            return queryset
        # Если обычный пользователь, то показываем только его отчеты.
        else:
            return queryset.filter(owner=self.request.user)


class MainListView(ListView):
    model = Article
    template_name = 'mailing/main_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Кеширование данных.
        if settings.CACHE_ENABLED:
            key = f'main_page'
            subjects = cache.get(key)
            if subjects is None:
                cache_timeout = 60 * 2  # Время жизни кеша, в секундах

                # Добавляем данные для отображения на главной странице
                mailing_count = Mailing.objects.count()
                mailing_active_count = Mailing.objects.filter(status='started').count()

mailing/templates/mailing/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Mailing service</title>
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
{% include 'mailing/includes/inc_mailing_menu.html' %}

{% block content %}
{% endblock %}
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="container">
        <div class="row">
            <div class="col-3 col-md">
                <small class="d-block mb-3 text-muted">{{ user.email|default:"Вы не авторизованны" }}</small>
            </div>
            <div class="col-3 col-md">
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'mailing:main_page' %}">Главная</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="text-muted" href="{% url 'mailing:mailings_list' %}">Рассылки</a></li>
                    {% endif %}
                    {% if not user.is_staff and user.is_authenticated or user.is_superuser %}
                    <li><a class="text-muted" href="{% url 'mailing:clients_list' %}">Клиенты</a></li>
                    <li><a class="text-muted" href="{% url 'mailing:report_list' %}">Отчеты</a></li>
                    <li><a class="text-muted" href="{% url 'users:users_list' %}">Пользователи</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="col-3 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="{% url 'blog:blog_list' %}">Наш блог</a></li>
                </ul>
            </div>
        </div>
    </div>
</footer>

<script src="{% static '/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

mailing/templates/mailing/client_form.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="container">
    <div class="card">
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a class="btn btn-warning" href="{% url 'mailing:clients_list' %}"
                           style="margin-left: 20px;">Отмена</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

mailing/templates/mailing/client_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Клиенты</h1>
    <p class="lead">На этой страницы вы можете добавить, удалить и отредактировать клиентов для рассылки.</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <a class="btn btn-lg btn-primary" style="margin-left: 102px;" href="{% url 'mailing:clients_create' %}">Добавить
        клиента</a>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h5 class="card-title">ФИО</h5>
                        </div>
                        <div class="col-sm-3">
                            <h5 class="card-title">Email клиента</h5>
                        </div>
                        <div class="col-sm-3">
                            <h5 class="card-title">Комментарий</h5>
                        </div>
                        <div class="col-sm-3">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in object_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.full_name }}</p>
                        </div>
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.email }}</p>
                        </div>
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.comment|slice:":25" }}</p>
                        </div>
                        <div class="col-sm-3">
                            <a href="{% url 'mailing:clients_edit' object.pk %}"
                               class="btn btn-sm btn-block btn-outline-primary">Редактировать</a>
                            <a href="{% url 'mailing:clients_delete' object.pk %}"
                               class="btn btn-sm btn-danger">Удалить</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/mailing_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Рассылки</h1>
    <p class="lead">На этой страницы вы можете создавать, редактировать и удалять рассылки.</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    {% if not user.is_staff or user.is_superuser %}
    <a class="btn btn-lg btn-primary" style="margin-left: 102px;" href="{% url 'mailing:mailings_create' %}">Создать
        рассылку</a>
    {% endif %}
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h5 class="card-title">Имя рассылки</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Время</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Периодичность</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Статус</h5>
                        </div>
                        <div class="col-sm-3">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in object_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.mailing_name }}</p>
                        </div>
                        <div class="col-sm-2">
                            <p class="card-text">{{ object.time }}</p>
                        </div>
                        <div class="col-sm-2">
                            <p class="card-text">{{ object.period }}</p>
                        </div>
                        <div class="col-sm-2">
                            <p class="card-text">{{ object.status }}</p>
                        </div>
                        <div class="col-sm-3">
                            <a href="{% url 'mailing:mailings_edit' object.pk %}"
                               class="btn btn-sm btn-block btn-outline-primary">Редактировать</a>
                            {% if not user.is_staff or user.is_superuser %}
                            <a href="{% url 'mailing:mailings_delete' object.pk %}" class="btn btn-sm btn-danger">Удалить</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/mailinglog_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Отчеты</h1>
    <p class="lead">Здесь вы можете просматривать автоматические созданные отчеты для рассылок.</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
    <a class="btn btn-lg btn-primary" style="margin-left: 102px;" href="{% url 'mailing:mailings_create' %}">Создать
        новую рассылку</a>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <h5 class="card-title">Имя рассылки</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Статус</h5>
                        </div>
                        <div class="col-sm-5">
                            <h5 class="card-title">Данные по клиентам</h5>
                        </div>
                        <div class="col-sm-3">
                            <h5 class="card-title">Сообщение об ошибке</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in object_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-2">
                            <p class="card-text">{{ object.mailing_name }}</p>
                        </div>
                        <div class="col-sm-2">
                            <p class="card-text">{{ object.status }}</p>
                            <p class="card-text">Время последней попытки: {{ object.last_mailing }}</p>
                        </div>
                        <div class="col-sm-5">
                            <p class="card-text">ФИО клиентов: {{ object.clients_full_name }}</p>
                            <p class="card-text">Email клиентов: {{ object.clients_email }}</p>
                        </div>
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.error_message }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}

mailing/templates/mailing/main_page.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Главная</h1>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <h5 class="card-title" style="font-size: 25px; text-align: center;">Рассылок всего</h5>
                        </div>
                        <div class="col-sm-4">
                            <h5 class="card-title" style="font-size: 25px; text-align: center;">Активных рассылок</h5>
                        </div>
                        <div class="col-sm-4">
                            <h5 class="card-title" style="font-size: 25px; text-align: center;">Клиенты для рассылок</h5>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-4">
                            <p class="card-text" style="font-size: 30px; text-align: center;">{{ mailing_count }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p class="card-text" style="font-size: 30px; text-align: center;">{{ mailing_active_count }}</p>
                        </div>
                        <div class="col-sm-4">
                            <p class="card-text" style="font-size: 30px; text-align: center;">{{ client_count }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-6">
            <div class="card mb-4 box-shadow" style="height: 700px;">
                <div class="card-header">
                    <img src="/media/{{ object.preview }}" style="max-width: 550%; height: auto;"
                         class="card-img-bottom">
                    <h4 class="my-0 font-weight-normal">{{ object.title }}</h4>
                </div>
                <div class="card-body d-flex flex-column">
                    <div class="mt-auto">
                        <p class="card-title pricing-card-title" style="text-align: left;">
                            {{ object.content|slice:":340" }}...</p>
                    </div>
                    <div class="mt-auto">
                        <a href="{% url 'blog:blog_item' object.pk %}"
                           class="btn btn-lg btn-block btn-outline-primary">Читать</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}