blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from blog.apps import BlogConfig
from blog.views import BlogListView, BlogDetailView

app_name = BlogConfig.name

urlpatterns = [
    path('', cache_page(60 * 2)(BlogListView.as_view()), name='blog_list'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_item'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mailing.urls', namespace='mailing')),
    path('users/', include('users.urls', namespace='users')),
    path('blog/', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView
from django.urls import path

from users.apps import UsersConfig
from users.views import RegisterView, ProfileView, VerifyEmailView, LogoutUserView, UserListView, UserUpdateView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutUserView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('verify_email/<str:token>/', VerifyEmailView.as_view(), name='verify_email'),

    path('users_list/', UserListView.as_view(), name='users_list'),
    path('users_list/edit/<int:pk>/', UserUpdateView.as_view(), name='users_edit'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone_number = models.CharField(max_length=35, verbose_name='Телефонный номер', **NULLABLE)
    confirmation_token = models.CharField(max_length=200, verbose_name='Токен подтверждения', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from mailing.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Скрытие лишних подсказок
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''


class UserProfileForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone_number',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Скрытие поля password
        self.fields['password'].widget = forms.HiddenInput()


class UserForManagerForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'first_name', 'last_name', 'phone_number', 'is_active',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Делаем поля не доступными к редактированию.
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['first_name'].widget.attrs['readonly'] = True
        self.fields['last_name'].widget.attrs['readonly'] = True
        self.fields['phone_number'].widget.attrs['readonly'] = True

        # Добавление чекбокса для is_active
        self.fields['is_active'].widget = forms.CheckboxInput()

        # Скрытие поля password
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import secrets

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.core.mail import send_mail
from django.http import Http404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, RedirectView, ListView
from users.forms import UserRegisterForm, UserProfileForm, UserForManagerForm

from config import settings
from users.models import User


class LogoutUserView(LoginRequiredMixin, LogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('mailing:main_page')

    def form_valid(self, form):
        # Сохранение в оперативную память (без добавление в БД).
        user = form.save(commit=False)
        # Пользователь неактивен, пока не подтвердит email.
        user.is_active = False
        # Генерируем токен, через secrets, и сохраняет его в поле пользователя.
        user.confirmation_token = secrets.token_urlsafe(30)
        user.save()

        # Создаем ссылку с токеном на следующий контроллер-представление.
        verification_link = self.request.build_absolute_uri(
            reverse_lazy('users:verify_email', kwargs={'token': user.confirmation_token}),
        )

        # Отправляем письмо с ссылкой-токеном.
        send_mail(
            subject='Верификация аккаунта',
            message=f'Осталось только подтвердить ваш аккаунт, перейдя по ссылке: {verification_link}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


class VerifyEmailView(RedirectView):
    # Устанавливает перенаправление как временное (а не постоянное).
    permanent = False
    # Устанавливает сохранение параметров запроса и включение их в целевой URL после перенаправления.
    query_string = True

    def get_redirect_url(self, *args, **kwargs):
        # Получает токен из URL.
        token = kwargs.get('token')
        try:
            # Ищет по токену пользователя с таким же токеном.
            user = User.objects.get(confirmation_token=token)
            # Активация пользователя.
            user.is_active = True
            # Удаление токена из поля пользователя (опционально).
            user.confirmation_token = ''
            user.save()
            return reverse('users:login')
        except User.DoesNotExist:
            print('Неверный токен')
            # Если токен неверный или истек, можно перенаправить на страницу с ошибкой.
            return reverse('users:login')


class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('mailing:main_page')

    # Что бы не пришлось на страницу профиля передавать pk.
    def get_object(self, queryset=None):
        return self.request.user


class UserListView(LoginRequiredMixin, ListView):
    model = User

    def get_queryset(self):
        queryset = super().get_queryset()

        # Если пользователь is_staff=True, то показываем всех обычных пользователей.
        if self.request.user.is_staff:
            return queryset.exclude(is_staff=True)
        # Если пользователь is_staff=False, то вызываем ошибку.
        else:
            raise Http404


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserForManagerForm
    success_url = reverse_lazy('users:users_list')

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)

        # Если пользователь is_staff=True, то доступ разрешен к редактированию обычных пользователя.
        if self.request.user.is_staff and not self.object.is_staff:
            return self.object
        else:
            raise Http404('Доступ запрещен')

users/templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: -webkit-box;
            display: flex;
            -ms-flex-align: center;
            -ms-flex-pack: center;
            -webkit-box-align: center;
            align-items: center;
            -webkit-box-pack: center;
            justify-content: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 500px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body class="text-center">
<form class="form-signin" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card p-5">
        <h4 class="mt-5 mb-3">Авторизация</h4>
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>

        <p class="mt-5 mb-3 text-muted">&copy; 2017-2024</p>
    </div>
</form>
</body>
</html>

users/templates/users/register.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: -webkit-box;
            display: flex;
            -ms-flex-align: center;
            -ms-flex-pack: center;
            -webkit-box-align: center;
            align-items: center;
            -webkit-box-pack: center;
            justify-content: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 430px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body class="text-center">
<form class="form-signin" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card p-5">
        <h4 class="mt-5 mb-3">Регистрация нового профиля</h4>
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Зарегистрироваться</button>

        <p class="mt-5 mb-3">Вам на почту должно прийти письмо с верификацией аккаунта!</p>
    </div>
</form>
</body>
</html>

users/templates/users/user_form.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>

    <style>
        html,
        body {
            height: 100%;
        }

        body {
            display: -ms-flexbox;
            display: -webkit-box;
            display: flex;
            -ms-flex-align: center;
            -ms-flex-pack: center;
            -webkit-box-align: center;
            align-items: center;
            -webkit-box-pack: center;
            justify-content: center;
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #f5f5f5;
        }

        .form-signin {
            width: 100%;
            max-width: 430px;
            padding: 15px;
            margin: 0 auto;
        }

        .form-signin .checkbox {
            font-weight: 400;
        }

        .form-signin .form-control {
            position: relative;
            box-sizing: border-box;
            height: auto;
            padding: 10px;
            font-size: 16px;
        }

        .form-signin .form-control:focus {
            z-index: 2;
        }

        .form-signin input[type="email"] {
            margin-bottom: -1px;
            border-bottom-right-radius: 0;
            border-bottom-left-radius: 0;
        }

        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
    </style>

    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">

</head>

<body class="text-center">
<form class="form-signin" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="card p-5">
        <h4 class="mt-5 mb-3">Редактирование аккаунта</h4>
        {{ form.as_p }}
        <button class="btn btn-lg btn-primary btn-block" type="submit">Сохранить изменения</button>

        <p class="mt-5 mb-3 text-muted">&copy; 2017-2024</p>
    </div>
</form>
</body>
</html>

users/templates/users/user_list.html
{% extends 'mailing/base.html' %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Пользователи сервиса</h1>
    <p class="lead">На этой страницы вы можете просматривать и отключать пользователей сервиса.</p>
</div>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-left">
</div>

<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <h5 class="card-title">Email</h5>
                        </div>
                        <div class="col-sm-3">
                            <h5 class="card-title">Имя и фамилия</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Телефонный номер</h5>
                        </div>
                        <div class="col-sm-2">
                            <h5 class="card-title">Статус пользователя</h5>
                        </div>
                        <div class="col-sm-2">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% for object in object_list %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="card-text">{{ object.email }}</p>
                        </div>
                        <div class="col-sm-3">
                            {% if object.first_name %}
                            <p class="card-text">{{ object.first_name }} {{ object.last_name }}</p>
                            {% else %}
                            <p class="card-text">Не указан</p>
                            {% endif %}
                        </div>
                        <div class="col-sm-2">
                            {% if object.phone_number %}
                            <p class="card-text">{{ object.phone_number }}</p>
                            {% else %}
                            <p class="card-text">Не указан</p>
                            {% endif %}
                        </div>
                        <div class="col-sm-2">
                            {% if object.is_active %}
                            <p class="card-text">Активен</p>
                            {% else %}
                            <p class="card-text">Заблокирован</p>
                            {% endif %}
                        </div>
                        <div class="col-sm-2">
                            <a href="{% url 'users:users_edit' object.pk %}"
                               class="btn btn-sm btn-block btn-outline-primary">Редактировать</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endfor %}
{% endblock %}